# Generated by Django 5.1.3 on 2024-12-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_trainingschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='country',
            new_name='city',
        ),
    ]
