# Generated by Django 5.1.3 on 2024-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_country_player_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
