# Generated by Django 5.1.3 on 2024-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_chatmessage_image_alter_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
