# Generated by Django 5.1.3 on 2024-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_uploadedimage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='time',
            field=models.TimeField(max_length=15),
        ),
    ]
