# Generated by Django 5.1.3 on 2024-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_chatmessage_options_alter_chatmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingschedule',
            name='date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='time',
            field=models.TimeField(),
        ),
    ]
