# Generated by Django 5.2.1 on 2025-05-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_trainingschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='bukti_transfer/'),
        ),
    ]
