# Generated by Django 5.1.3 on 2025-06-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_registrationrequest_remove_profile_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
